CREATE TABLE IF NOT EXISTS "USERS" (
	USER_ID UUID DEFAULT RANDOM_UUID() NOT NULL,
	CHAT_ID BIGINT NOT NULL,
	USERNAME CHARACTER VARYING(50) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT USERS_CHAT_ID_UQ UNIQUE (CHAT_ID),
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID),
	CONSTRAINT USERS_USERNAME_UQ UNIQUE (USERNAME)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_6 ON "USERS" (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS USERS_CHAT_ID_UQ_INDEX_6 ON "USERS" (CHAT_ID);
CREATE UNIQUE INDEX IF NOT EXISTS USERS_USERNAME_UQ_INDEX_6 ON "USERS" (USERNAME);

COMMENT ON TABLE users IS 'Пользователи';
COMMENT ON COLUMN users.user_id IS 'Уникальный идентификатор пользователя (UUID)';
COMMENT ON COLUMN users.chat_id IS 'Идентификатор пользователя в телеграмме';
COMMENT ON COLUMN users.username IS 'Имя пользователя (уникальное)';
COMMENT ON COLUMN users.created_at IS 'Дата и время создания записи';

CREATE TABLE IF NOT EXISTS SAVED_LINKS (
	LINK_ID UUID DEFAULT RANDOM_UUID() NOT NULL,
	USER_ID UUID NOT NULL,
	ORIGIN_URL CHARACTER VARYING(2048) NOT NULL,
	TITLE CHARACTER VARYING(5000),
	DESCRIPTION CHARACTER VARYING(5000),
	IMAGE_URL CHARACTER VARYING(2048),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT SAVED_LINKS_PK PRIMARY KEY (LINK_ID),
	CONSTRAINT SAVED_LINKS_UNIQUE UNIQUE (LINK_ID,USER_ID),
	CONSTRAINT SAVED_LINKS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_C ON SAVED_LINKS (LINK_ID);
CREATE UNIQUE INDEX IF NOT EXISTS SAVED_LINKS_UNIQUE_INDEX_C ON SAVED_LINKS (LINK_ID,USER_ID);
CREATE INDEX IF NOT EXISTS SAVED_LINKS_USERS_FK_INDEX_C ON SAVED_LINKS (USER_ID);
CREATE INDEX IF NOT EXISTS SAVED_LINKS_USER_ID_DESCRIPTION_IDX ON SAVED_LINKS (USER_ID,DESCRIPTION);
CREATE INDEX IF NOT EXISTS SAVED_LINKS_USER_ID_TITLE_IDX ON SAVED_LINKS (USER_ID,TITLE);
CREATE INDEX IF NOT EXISTS SAVED_LINKS_USER_ID_TITLE_DESCRIPT_IDX ON SAVED_LINKS (USER_ID,TITLE,DESCRIPTION);

COMMENT ON TABLE saved_links IS 'Сохраненные ссылки';
COMMENT ON COLUMN saved_links.origin_url IS 'Ссылка';
COMMENT ON COLUMN saved_links.title IS 'Заголовок';
COMMENT ON COLUMN saved_links.description IS 'Описание';
COMMENT ON COLUMN saved_links.image_url IS 'Ссылка на картинку';
COMMENT ON COLUMN saved_links.created_at IS 'Дата и время добавления';
COMMENT ON COLUMN saved_links.user_id IS 'Пользователь';

CREATE TABLE IF NOT EXISTS SAVED_LINK_TAGS (
	ID UUID DEFAULT RANDOM_UUID() NOT NULL,
	SAVED_LINK_LINK_ID UUID NOT NULL,
	TAGS CHARACTER(250) NOT NULL,
	CONSTRAINT SAVED_LINK_TAGS_PK PRIMARY KEY (ID),
	CONSTRAINT SAVED_LINK_TAGS_SAVED_LINKS_FK FOREIGN KEY (SAVED_LINK_LINK_ID) REFERENCES SAVED_LINKS(LINK_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_2 ON SAVED_LINK_TAGS (ID);
CREATE INDEX IF NOT EXISTS SAVED_LINK_TAGS_SAVED_LINKS_FK_INDEX_2 ON SAVED_LINK_TAGS (SAVED_LINK_LINK_ID);
CREATE INDEX IF NOT EXISTS SAVED_LINK_TAGS_SAVED_LINK_LINK_ID_IDX ON SAVED_LINK_TAGS (SAVED_LINK_LINK_ID,TAGS);
CREATE INDEX IF NOT EXISTS SAVED_LINK_TAGS_TAGS_IDX ON SAVED_LINK_TAGS (TAGS);

COMMENT ON TABLE saved_link_tags IS 'Теги';
COMMENT ON COLUMN saved_link_tags.id IS 'Уникальный идентификатор (UUID)';
COMMENT ON COLUMN saved_link_tags.saved_link_link_id IS 'Идентификатор ссылки';
COMMENT ON COLUMN saved_link_tags.tags IS 'Теги';